services:
  postgres:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
